name: prueba_tecnica_agenda
description: "Agenda Escolar"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0-24.0.dev

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  lottie: ^3.3.1
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test: ^1.25.15

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/animations/
